apiVersion: v1
kind: Service
metadata:
  name: apistub
  labels:
    app: apistub
spec:
  ports:
    - port: 8888
      name: http
  selector:
    app: apistub
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apistub-v1
  labels:
    app: apistub
    version: v1
spec:
  selector:
    matchLabels:
      app: apistub
  replicas: 1
  template:
    metadata:
      labels:
        app: apistub
        version: v1
    spec:
      containers:
        - name: apistub
          image: apistub
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
---
