#hystrix:
#  command.apiCall:
#    circuitBreaker.enabled: false
#    fallback.enabled: false
#    execution.timeout.enabled: false
#
#  threadpool.apiThreadPool:
#    coreSize: 15
#    maximumSize: 25
#    maxQueueSize: -1
#    keepAliveTimeMinutes: 1
#    allowMaximumSizeToDivergeFromCoreSize: true

hystrix:
  command.apiCall:
    execution.isolation:
      strategy: 'SEMAPHORE'
      semaphore.maxConcurrentRequests: 25
    circuitBreaker.enabled: false
    fallback.enabled: false
    execution.timeout.enabled: false