hystrix:
  command:
    default:
      execution.timeout.enabled: false
      circuitBreaker.enabled: false
      fallback.enabled: false
    apiCall:
      circuitBreaker.errorThresholdPercentage: 99
      circuitBreaker.requestVolumeThreshold: 20
      metrics.rollingStats.timeInMilliseconds: 10000
      execution.isolation.thread.timeoutInMilliseconds: 2000

  threadpool.apiThreadPool:
    coreSize: 15
    maximumSize: 20
    maxQueueSize: -1
    keepAliveTimeMinutes: 1
    allowMaximumSizeToDivergeFromCoreSize: true

management.endpoints.web:
  exposure.include: health,prometheus,hystrix
  base-path: /
  path-mapping:
    prometheus: metrics