apiVersion: v1
kind: Service
metadata:
  name: sample-hystix
  labels:
    app: sample-hystix
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: sample-hystix_mapping
      prefix: /sample-hystix/
      service: sample-hystix:8080
      tls: upstream
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: sample-hystix
  sessionAffinity: None
    type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hystix-v1
  labels:
    app: sample-hystix
    version: v1
spec:
  selector:
    matchLabels:
      app: sample-hystix
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-hystix
        version: v1
    spec:
      containers:
        - name: sample-hystix
          image: sample-hystix
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
---
