apiVersion: v1
kind: Service
metadata:
  name: hystrixsample
  labels:
    app: hystrixsample
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: hystrixsample_mapping
      prefix: /hystrixsample/
      service: hystrixsample:8080
      tls: upstream
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: hystrixsample
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hystrixsample-v1
  labels:
    app: hystrixsample
    version: v1
spec:
  selector:
    matchLabels:
      app: hystrixsample
  replicas: 1
  template:
    metadata:
      labels:
        app: hystrixsample
        version: v1
    spec:
      containers:
        - name: hystrixsample
          image: hystrixsample
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 600m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
---
